### ISSUE TITLE
Help :-)

### ISSUE THREAD

**Issue by AdoZiad** [zewish/php-postfix-maillog-importer#1]
Hello,

I would like to use your importer to get the emails sent on my sever but i'm having some trouble...

Here's the error i'm getting:

`PHP Warning:  PDO::quote() expects parameter 1 to be string, object given in /batch/postfix/maillogimporter/writer/mysql.php on line 85

Warning: PDO::quote() expects parameter 1 to be string, object given in /batch/postfix/maillogimporter/writer/mysql.php on line 85
PHP Fatal error:  Uncaught exception 'MaillogImporter\MaillogException' with message 'Could not execute UPDATE database statement: "UPDATE `email_log` SET `date_updated` = , `status` = 'sent', `info` = IF(`info` = "", '250 ok 1444401334 qp 4796' , CONCAT(`info`, "\n", '250 ok 1444401334 qp 4796')) WHERE `postfix_message_id` = '2E1A71600DC'"' in /batch/postfix/maillogimporter/writer/mysql.php:95
Stack trace:
#0 /batch/postfix/maillogimporter/writer/mysql.php(78): MaillogImporter\Writer\MySql->_updateEmailData('2E1A71600DC', Object(DateTime), 'sent', '250 ok 14444013...')
#1 /batch/postfix/maillogimporter/parser.php(90): MaillogImporter\Writer\MySql->updateData('2E1A71600DC', Array)
#2 /batch/postfix/maillogimporter/parser.php(59): MaillogImporter\Parser->_updateData(Array)
#3 /batch/postfix/maillogimporter/parser.php(24): MaillogImporter\Parser->_parseSendStatuses('Oct  9 16:35:35...')
#4 /batch/postfix/maillogimporter/fileimporter.php(48): MaillogImporter\Parser->parseLine('Oct  9 16:35:35...')
#5 /batch/postfix/maillog-importer.php(34): MaillogImporter\FileImporter->import(Object(MaillogImporter\Writer\MySql))
#6 {main}

  thrown in /batch/postfix/maillogimporter/writer/mysql.php on line 95

Fatal error: Uncaught exception 'MaillogImporter\MaillogException' with message 'Could not execute UPDATE database statement: "UPDATE `email_log` SET `date_updated` = , `status` = 'sent', `info` = IF(`info` = "", '250 ok 1444401334 qp 4796' , CONCAT(`info`, "\n", '250 ok 1444401334 qp 4796')) WHERE `postfix_message_id` = '2E1A71600DC'"' in /batch/postfix/maillogimporter/writer/mysql.php:95
Stack trace:
#0 /batch/postfix/maillogimporter/writer/mysql.php(78): MaillogImporter\Writer\MySql->_updateEmailData('2E1A71600DC', Object(DateTime), 'sent', '250 ok 14444013...')
#1 /batch/postfix/maillogimporter/parser.php(90): MaillogImporter\Writer\MySql->updateData('2E1A71600DC', Array)
#2 /batch/postfix/maillogimporter/parser.php(59): MaillogImporter\Parser->_updateData(Array)
#3 /batch/postfix/maillogimporter/parser.php(24): MaillogImporter\Parser->_parseSendStatuses('Oct  9 16:35:35...')
#4 /batch/postfix/maillogimporter/fileimporter.php(48): MaillogImporter\Parser->parseLine('Oct  9 16:35:35...')
#5 /batch/postfix/maillog-importer.php(34): MaillogImporter\FileImporter->import(Object(MaillogImporter\Writer\MySql))
#6 {main}

  thrown in /batch/postfix/maillogimporter/writer/mysql.php on line 95`

I don't see what's wrong or how to fix this. Any hint would be appreciated.

Thanks in advance for your help.

Kind regards.

**Comment by zewish** [comment]
Hey there! I wrote this one centuries ago, and I'm no longer using it actively, so I'm not really sure if it still works.

Anyway, from what I see the date format in your mail.log file may be different. You may want to have a look at the config value of "dateTimeRegex" and fix this: https://github.com/zewish/php-postfix-maillog-importer/blob/master/configs/main.php.

I suppose something like this: 'dateTimeRegex' => '^([a-zA-Z]{3} \d \d{2}:\d{2}:\d{2})' will probably fix your problem.

**Comment by AdoZiad** [comment]
Hi,

Thanks for your quick reaction much appreciated :-)

Unfortunately i still have error:
`PHP Fatal error:  Uncaught exception 'MaillogImporter\MaillogException' with message 'Could not match line with the date regex: "Sep 23 21:10:18 3ecs postfix/postfix-script[2516]: starting the Postfix mail system
"' in /batch/postfix/maillogimporter/fileimporter.php:51
Stack trace:
#0 /batch/postfix/maillog-importer.php(34): MaillogImporter\FileImporter->import(Object(MaillogImporter\Writer\MySql))
#1 {main}
  thrown in /batch/postfix/maillogimporter/fileimporter.php on line 51

Fatal error: Uncaught exception 'MaillogImporter\MaillogException' with message 'Could not match line with the date regex: "Sep 23 21:10:18 3ecs postfix/postfix-script[2516]: starting the Postfix mail system
"' in /batch/postfix/maillogimporter/fileimporter.php:51
Stack trace:
#0 /batch/postfix/maillog-importer.php(34): MaillogImporter\FileImporter->import(Object(MaillogImporter\Writer\MySql))
#1 {main}
  thrown in /batch/postfix/maillogimporter/fileimporter.php on line 51`

Thanks again for any help you could give.

Kind regards.

**Comment by zewish** [comment]
Ah, now I see, wanna try this one?
'dateTimeRegex' => '^([a-zA-Z]{3} \d{1,2} \d{2}:\d{2}:\d{2})'

**Comment by AdoZiad** [comment]
Now i get this:


`PHP Fatal error:  Uncaught exception 'MaillogImporter\MaillogException' with message 'Could not match line with the date regex: "Oct  1 03:28:01 3ecs postfix/pickup[22027]: C77DD160480: uid=0 from=<root>
"' in /batch/postfix/maillogimporter/fileimporter.php:51
Stack trace:
#0 /batch/postfix/maillog-importer.php(34): MaillogImporter\FileImporter->import(Object(MaillogImporter\Writer\MySql))
#1 {main}
  thrown in /batch/postfix/maillogimporter/fileimporter.php on line 51

Fatal error: Uncaught exception 'MaillogImporter\MaillogException' with message 'Could not match line with the date regex: "Oct  1 03:28:01 3ecs postfix/pickup[22027]: C77DD160480: uid=0 from=<root>
"' in /batch/postfix/maillogimporter/fileimporter.php:51
Stack trace:
#0 /batch/postfix/maillog-importer.php(34): MaillogImporter\FileImporter->import(Object(MaillogImporter\Writer\MySql))
#1 {main}
  thrown in /batch/postfix/maillogimporter/fileimporter.php on line 51`

**Comment by zewish** [comment]
Well, then I'm open to any PRs fixing this :)

**Comment by zewish** [comment]
It's probably the "uid=0" in the line that breaks the parsing. Take a look at https://github.com/zewish/php-postfix-maillog-importer/blob/master/maillogimporter/parser.php -> the _parseExpiredStatuses and _parseSendStatuses functions.

**Comment by AdoZiad** [comment]
I changed the regex to the following:
'dateTimeRegex' => '^(?:(?:(?:(?:(?:0[13578]|1[02])\/(?:0[1-9]|[1-2][0-9]|3[01]))|(?:(?:0[469]|11)\/(?:0[1-9]|[1-2][0-9]|30))|(?:02\/(?:0[1-9]|1[0-9]|2[0-8]))))\/\d{4}|02\/29\/(?:(?:\d{2}(?:04|08|[2468][048]|[13579][26]))|(?:(?:[02468][048])|[13579][26])00))(?:\s(?:0[1-9]|1[0-2]):[0-5][0-9]:[0-5][0-9]\s(?:AM|PM|am|pm))?$'

and now i got this...:
`PHP Fatal error:  Uncaught exception 'MaillogImporter\MaillogException' with message 'Could not match line with the date regex: "Sep 23 21:10:18 3ecs postfix/postfix-script[2516]: starting the Postfix mail system
"' in /batch/postfix/maillogimporter/fileimporter.php:51
Stack trace:
#0 /batch/postfix/maillog-importer.php(34): MaillogImporter\FileImporter->import(Object(MaillogImporter\Writer\MySql))
#1 {main}
  thrown in /batch/postfix/maillogimporter/fileimporter.php on line 51

Fatal error: Uncaught exception 'MaillogImporter\MaillogException' with message 'Could not match line with the date regex: "Sep 23 21:10:18 3ecs postfix/postfix-script[2516]: starting the Postfix mail system
"' in /batch/postfix/maillogimporter/fileimporter.php:51
Stack trace:
#0 /batch/postfix/maillog-importer.php(34): MaillogImporter\FileImporter->import(Object(MaillogImporter\Writer\MySql))
#1 {main}
  thrown in /batch/postfix/maillogimporter/fileimporter.php on line 51`

**Comment by AdoZiad** [comment]
here's a typical log line (if it helps...):

May 31 17:14:35 3ecs postfix/smtp[30138]: 93DF416052C: to=xxx@xxx.com, relay=mailhost1.xxx.com[xxx.x.xxx.xxx]:25, delay=44, delays=0.01/0/43/1.3, dsn=2.0.0, status=sent (250 2.0.0 u4VFEWn6008619 Message accepted for delivery)

**Comment by AdoZiad** [comment]
May 31 17:14:35 3ecs postfix/smtp[30138]: 93DF416052C: **to=xxx@xxx.com**, relay=mailhost1.xxx.com[xxx.x.xxx.xxx]:25, delay=44, delays=0.01/0/43/1.3, dsn=2.0.0, status=sent (250 2.0.0 u4VFEWn6008619 Message accepted for delivery)
