### ISSUE TITLE
Uncaught exception 'AutloaderException'

### ISSUE THREAD

**Issue by shebinhere** [zewish/php-postfix-maillog-importer#5]
I am configuring it with mongo
Stack trace - 
PHP Fatal error:  Uncaught exception 'AutloaderException' with message 'File not found: "/usr/local/snp/php-postfix/mongoclient.php".' in /usr/local/snp/php-postfix/base/load.php:16
Stack trace:
#0 [internal function]: {closure}('MongoClient')
#1 /usr/local/snp/php-postfix/maillogimporter/writer/mongo.php(20): spl_autoload_call('MongoClient')
#2 /usr/local/snp/php-postfix/maillog-importer.php(31): MaillogImporter\Writer\Mongo->__construct()
#3 {main}
  thrown in /usr/local/snp/php-postfix/base/load.php on line 16

Please help!

**Comment by zewish** [comment]
Hey @shebinhere, I'm no longer using this importer.
Feel free to patch the issues you have and do a PR if you want.
